<script lang="ts" setup>
interface Props {
	title: string
	submitButton?: Function
}
const props = defineProps<Props>()

// These phrases are generated by @enfipy and ChatGPT.
const randomPhrases = [
	"Remember, Faterium polls can only be created in amazing communities.",
	"Remember, the only thing more powerful than a supercomputer is the user who's forgotten their password.",
	"Remember, the true measure of intelligence is how many ASCII cats one can fit in a tweet.",
	"Remember, the only thing more important than backup is the location of the backup.",
	"Remember, the only thing more confusing than C++ code is the documentation for C++ code.",
	"Remember, the only thing more valuable than a bitcoin is the electricity used to mine it.",
	"Remember, the only thing more confusing than a blockchain is a private blockchain.",
	"Remember, the only thing more annoying than a coworker who won't comment their code is a coworker who comments every single line of their code.",
	"Remember, the only thing more confusing than reading someone else's code is reading your own code from 6 months ago.",
	"Remember, the only thing more depressing than a broken computer is a broken computer and no backup.",
	"Remember, the only thing more annoying than a spam email is a spam email with a catchy subject line.",
	"Remember, the only thing more frustrating than a slow computer is a fast computer with a slow internet connection.",
]

function getRandomPhrase() {
	const i = Math.floor(Math.random() * randomPhrases.length)
	return randomPhrases[i]
}

const description = getRandomPhrase()
</script>

<template lang="pug">
main.content.create-page
	div.create-wrapper
		h1.title {{ title }}
		p.description {{ description }}
		form.create-form(type="group" @submit.prevent="submitButton")
			slot
</template>

<style lang="scss">
.content.create-page {
	@apply flex flex-col h-full w-100vw relative justify-center items-center;
	.create-wrapper {
		@apply flex flex-col justify-start items-start z-2 w-160 h-full pt-100px;
		h1.title {
			@apply text-4xl font-bold m-0 text-black;
		}
		p.description {
			@apply font-normal opacity-50 ml-0.4;
		}
		.create-form {
			@apply my-6 w-full;
			& > div {
				@apply my-4;
			}
			div.actions {
				@apply flex flex-row gap-4 mt-6 pb-20;
			}
		}
	}
}
</style>
